# Usa una imagen base con Rust
FROM rust:latest

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el código fuente dentro del contenedor
COPY PC2/rust/rust.rs .

# Compilar el código
RUN rustc rust.rs -o rust_program

# Definir el comando que ejecutará el programa
CMD ["./rust_program"]
